config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "requests#index"
  resources :users, only: [:edit, :update]
  resources :requests, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      get :approve
      get :unapprove
    end
  end
end

app/models/admission.rb
class Admission < ApplicationRecord
  belongs_to :request
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :request
  belongs_to :user
end

app/models/pass.rb
class Pass < ApplicationRecord
  has_many :users
  belongs_to :request

  validates :final_user_id, presence: true
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  has_one :admission, dependent: :destroy
  has_one :pass, dependent: :destroy
  accepts_nested_attributes_for :admission, allow_destroy: true
  accepts_nested_attributes_for :pass, allow_destroy: true

  mount_uploader :pdf, ImageUploader
  validates :title, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  has_many :requests
  has_many :passes
  has_many :comments

  validates :name, presence: true, uniqueness: true
  
end

app/controllers/admission_controller.rb
class AdmissionController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    binding.pry
    redirect_to root_path
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, request_id: params[:request_id])
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  def index
    request = Request.where(user_id: current_user.id)
    @request_unapproved = request.where(status: 1)
    @request_approved = request.where(status: 2)
    @request_deniel = request.where(status: 3)
    requested_id = Pass.where(requested_user: current_user.id).select(:request_id)
    approve = Request.where(id: requested_id)
    @approve_unapproved = approve.where(status: 1)
    @approve_approved = approve.where(status: 2)

  end

  def new
    @request = Request.new
    @request.admission
    @request.pass
  end

  def create
    @request = Request.new(request_params)
    if @request.pass.first_user_id.present?
      @request.pass.requested_user = @request.pass.first_user_id
    elsif @request.pass.second_user_id.present?
      @request.pass.requested_user = @request.pass.second_user_id
    elsif @request.pass.third_user_id.present?
      @request.pass.requested_user = @request.pass.third_user_id
    elsif @request.pass.final_user_id.present?
      @request.pass.requested_user = @request.pass.final_user_id
    end
    if @request.save
       redirect_to requests_path
    else
      flash.now[:alert] = '必須事項を入力してください'
      render :new
    end
  end


  def edit
    @request = Request.find(params[:id])
    @request.admission = Request.find(params[:id]).admission
    @request.pass = Request.find(params[:id]).pass
  end

  def update
    @request = Request.find(params[:id])
    if @request.update(request_params)
      @request.update(status: "1")
      redirect_to root_path
    else
      @request.admission = Request.find(params[:id]).admission
      @request.pass = Request.find(params[:id]).pass
      flash.now[:alert] = '必須事項を入力してください'
      render "edit"
    end
  end

  def destroy
    request = Request.find(params[:id])
    if request.destroy
      flash[:notice] = "削除が完了しました。"
      redirect_to root_url
    else
      flash[:alert] = "削除できませんでした。"
      redirect_to root_url
    end
  end

  def approve
    @pass = Pass.where(request_id: params[:id])
    if current_user.id == @pass.pluck(:first_user_id)[0]
      Pass.where( request_id: params[:id] ).update( requested_user: @pass.pluck(:second_user_id)[0])
    elsif current_user.id == @pass.pluck(:second_user_id)[0]
      Pass.where( request_id: params[:id] ).update( requested_user: @pass.pluck(:third_user_id)[0])
    elsif current_user.id == @pass.pluck(:third_user_id)[0]
      Pass.where( request_id: params[:id] ).update( requested_user: @pass.pluck(:final_user_id)[0])
    elsif current_user.id == @pass.pluck(:final_user_id)[0]
      Request.find(params[:id]).update(status: "2")
    end
    redirect_to root_path
  end

  def unapprove
    @pass = Pass.where(request_id: params[:id])
    Request.find(params[:id]).update(status: "3")
    redirect_to root_path
  end


  private
  def request_params
    params.require(:request).permit(:title,
                                    :pdf,
                                    :message,
                                    :user_id,
                                    :kind,
                                    :deadline,
                                    :status,
                                    admission_attributes: [:user_id,
                                                            :request_id,
                                                            :title,
                                                            :start,
                                                            :finish,
                                                            :detail,
                                                            :prace,
                                                            :aerial,
                                                            :firearm,
                                                            :campany,
                                                            :representative,
                                                            :tell,
                                                            :worker1,
                                                            :worker2,
                                                            :worker3,
                                                            :worker4,
                                                            :notice],
                                    pass_attributes: [:request_id,
                                                      :first_user_id,
                                                      :second_user_id,
                                                      :third_user_id,
                                                      :final_user_id,
                                                      :requested_user])
                              .merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Sealless
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
  .Wrapper
    = yield

app/views/requests/_header.html.haml
.notifications
  - flash.each do |key, value|
    = content_tag(:div, value, class: key)
.Header
  = link_to "Sealless", requests_path, class: "Header__logo"
  .Header__Box
    .Header__Box__Name
      = current_user.name
    = link_to edit_user_path(current_user) do
      = icon('fa', 'cog', class: "Header__Box__icon")
    = link_to destroy_user_session_path, method: :delete do
      = icon('fa', 'door-open', class: "Header__Box__icon")

app/views/requests/edit.html.haml
= javascript_include_tag 'new'
= render "header"
= form_with model: [@request], local: true do |form|
  .Base
    .Base__Textbox
      .Base__Textbox__Subtitle
        基本情報
      = form.text_field :title, placeholder: "タイトル", class: "Base__Textbox__Text-field"
      = form.text_area :message, placeholder: "内容", class: "Base__Textbox__Text-area"
      .Base__Textbox__Deadline
        希望納期:
        = form.datetime_select :deadline, {}, class: "Base__Textbox__Deadline__Pulldown"
    .Base__Pass
      .Base__Pass__Subtitle
        承認者一覧
      = form.fields_for :pass, @request.pass do |user|
        .Base__Pass__pulldown
          .Base__Pass__pulldown__first_user
            第1承認者 ：
            = user.collection_select :first_user_id, User.all, :id, :name, include_blank: true
          .Base__Pass__pulldown__second_user
            第2承認者 ：
            = user.collection_select :second_user_id, User.all, :id, :name, include_blank: true
          .Base__Pass__pulldown__third_user
            第3承認者 ：
            = user.collection_select :third_user_id, User.all, :id, :name, include_blank: true
          .Base__Pass__pulldown__final_user
            最終承認者：
            = user.collection_select :final_user_id, User.all, :id, :name, include_blank: true
  .Type
    %button{type: "button", class: "Type__Admission Active", id: "Admission" }
      入場許可
    %button{type: "button", class: "Type__Document", id: "Document" }
      書類承認
  = form.fields_for :admission, @request.admission do |i|
    .Form
      .Form__Admission
        .Form__Admission__Child
          .Form__Admission__Child__Subtitle
            作業情報
          .Form__Admission__Child__Datetime-Start
            作業開始日時:
            = i.datetime_select :start, {}, class: "Form__Admission__Child__Datetime-Start__Pulldown"
          .Form__Admission__Child__Datetime-Finish
            作業終了日時:
            = i.datetime_select :finish, {}, class: 'Form__Admission__Child__Datetime-Finish__Pulldown'
          = i.text_field :prace, placeholder: "場所", class: "Form__Admission__Child__Text-field"
          .Form__Admission__Child__Check-box
            高所作業：
            = i.check_box :aerial, class: "Form__Admission__Child__Check-box__Aerial"
          .Form__Admission__Child__Check-box
            火器使用：
            = i.check_box :firearm, class: "Form__Admission__Child__Check-box__Firearm"    
          .Form__Admission__Child__Check-box
            = i.text_area :notice, placeholder: "特記事項", class: "Form__Admission__Child__Text-area"
        .Form__Admission__Child
          .Form__Admission__Child__Subtitle
            作業者情報
          = i.text_field :campany, placeholder: "会社名", class: "Form__Admission__Child__Text-field"
          = i.text_field :representative, placeholder: "代表者名", class: "Form__Admission__Child__Text-field"
          = i.text_field :tell, placeholder: "000-0000-0000", class: "Form__Admission__Child__Text-field"
          = i.text_field :worker1, placeholder: "作業者1", class: "Form__Admission__Child__Text-field"
          = i.text_field :worker2, placeholder: "作業者2", class: "Form__Admission__Child__Text-field"
          = i.text_field :worker3, placeholder: "作業者3", class: "Form__Admission__Child__Text-field"
          = i.text_field :worker4, placeholder: "作業者4", class: "Form__Admission__Child__Text-field"
    .Form__Document
      - if @request.pdf.present?
        = image_tag @request.pdf.url, alt: "preview"
      %object{data: "@request.pdf.url", type: "application/pdf", height: "100%", width: "100%"}
      -# PDF実装用コメントアウト
      -# %embed{src: "@request.pdf.url", type: "application/pdf", height: "100%", width: "100%"}
      -# %iframe{src: "@request.pdf.url", type: "application/pdf", height: "100%", width: "100%"}
      %label{for: "pdf", class: "Form__Document--btn", id: "label-btn"}
        %pre.label-box__text-visible クリックして画像を変更
        = form.file_field :pdf, id: "pdf", class: "Hide-field"
  - if (@request.user_id == current_user.id)&&(@request.status == 1)
    = form.submit value: "登録", class: "Form__Send"
  - elsif (@request.user_id == current_user.id)&&(@request.status == 3)
    = form.submit value: "再登録", class: "Form__Send"
  - elsif @request.status == 2
  - else
    .Btn_box
      .Btn_box__Btn
        = link_to approve_request_path(params[:id]) do
          承認        
      .Btn_box__Btn
        = link_to unapprove_request_path(params[:id]) do
          否認

app/views/requests/index.html.haml
= javascript_include_tag 'index'
= render "header"
.Body
  .Switch
    %button{ class: "Switch__Request Active", id: "Request" }
      起案
    %button{ class: "Switch__Approve", id: "Approve" }
      承認
  = link_to "新規作成", new_request_path, class: "New-request"
  .Request
    .Request__Unapproved
      .Request__Unapproved__Title
        承認依頼中
        %table{border: 1, width: "100%"} 
          .Request__Unapproved__Title__column
            %tr 
              %th{width: "200"}
                %span{class: "Request__Unapproved__Title__Deniel"}否認済
                , 承認待タイトル
              %th
                詳細
              %th{width: "40"} 
                編集
              %th{width: "40"} 
                削除
          - @request_deniel.each do |f|
            %tr 
              %th
                .Request__Unapproved__Title__Deniel
                  = f.title.truncate(16)
              %th
                = f.message.truncate(8)
              %th
                = link_to edit_request_path(f.id) do
                  = icon('fa', 'cog', class: "Header__Box__icon")
              %th{ align: "center" }
                = link_to request_path(f.id), method: :delete do
                  = icon('fa', 'trash', class: "Header__Box__icon")
          - @request_unapproved.each do |f|
            %tr 
              %th
                = f.title.truncate(16)
              %th
                = f.message.truncate(8)
              %th
                = link_to edit_request_path(f.id) do
                  = icon('fa', 'cog', class: "Header__Box__icon")
              %th{ align: "center" }
                = link_to request_path(f.id), method: :delete do
                  = icon('fa', 'trash', class: "Header__Box__icon")
    .Request__Approved
      .Request__Approved__Title
        承認済
        %table{border: 1, width: "100%"} 
          .Request__Unapproved__Title__column
            %tr 
              %th{width: "200"} 
                タイトル
              %th
                詳細
              %th{width: "40"} 
                確認
          - @request_approved.each do |f|
            %tr 
              %th
                = f.title.truncate(16)
              %th
                = f.message.truncate(8)
              %th
                = link_to edit_request_path(f.id) do
                  = icon('fa', 'cog', class: "Header__Box__icon")
  .Approve
    .Approve__Unapproved
      .Approve__Unapproved__Title
        承認待ち
        %table{border: 1, width: "100%"} 
          .Approve__Unapproved__Title__column
            %tr 
              %th{width: "200"} 
                タイトル
              %th
                詳細
              %th{width: "50"} 
                依頼者
              %th{width: "40"} 
                詳細
          - @approve_unapproved.each do |f|
            %tr 
              %th
                = f.title.truncate(16)
              %th
                = f.message.truncate(8)
              %th
                = f.user.name
              %th
                = link_to edit_request_path(f.id) do
                  = icon('fa', 'cog', class: "Header__Box__icon")
    .Approve__Approved
      .Approve__Approved__Title
        承認済
        %table{border: 1, width: "100%"} 
          .Request__Unapproved__Title__column
            %tr 
              %th{width: "200"} 
                タイトル
              %th
                詳細
              %th{width: "40"} 
                確認
          - @approve_approved.each do |f|
            %tr 
              %th
                = f.title.truncate(16)
              %th
                = f.message.truncate(8)
              %th
                = link_to edit_request_path(f.id) do
                  = icon('fa', 'cog', class: "Header__Box__icon")
.Footer

app/views/requests/new.html.haml
= javascript_include_tag 'new'
= render "header"
= form_with model: [@request], local: true do |form|
  .Base
    .Base__Textbox
      .Base__Textbox__Subtitle
        基本情報
      .Base__Textbox__Required
        = form.text_field :title, placeholder: "タイトル", class: "Base__Textbox__Text-field"
        .Base__Textbox__Required__Asterisk
          *(必須項目)
      .Base__Textbox__Required
        = form.text_area :message, placeholder: "内容", class: "Base__Textbox__Text-area"
        .Base__Textbox__Required__Asterisk
          *
      .Base__Textbox__Deadline
        希望納期:
        = form.datetime_select :deadline, {}, class: "Base__Textbox__Deadline__Pulldown"
    .Base__Pass
      .Base__Pass__Subtitle
        承認者一覧
      = form.fields_for :pass, @request.build_pass do |user|
        .Base__Pass__pulldown
          .Base__Pass__pulldown__first_user
            第1承認者 ：
            = user.collection_select :first_user_id, User.all, :id, :name, include_blank: true
          .Base__Pass__pulldown__second_user
            第2承認者 ：
            = user.collection_select :second_user_id, User.all, :id, :name, include_blank: true
          .Base__Pass__pulldown__third_user
            第3承認者 ：
            = user.collection_select :third_user_id, User.all, :id, :name, include_blank: true
          .Base__Pass__pulldown__final_user__Required
            .Base__Pass__pulldown__final_user__Required--margin
              最終承認者： 
            = user.collection_select :final_user_id, User.all, :id, :name, include_blank: true
            .Base__Pass__pulldown__final_user__Required__Asterisk
              *
  .Type
    %button{type: "button", class: "Type__Admission Active", id: "Admission" }
      入場許可
    %button{type: "button", class: "Type__Document", id: "Document" }
      書類承認
  .Form
    .Form__Admission
      = form.fields_for :admission, @request.build_admission do |i|
        .Form__Admission__Child
          .Form__Admission__Child__Subtitle
            作業情報
          .Form__Admission__Child__Datetime-Start
            作業開始日時:
            = i.datetime_select :start, {}, class: "Form__Admission__Child__Datetime-Start__Pulldown"
          .Form__Admission__Child__Datetime-Finish
            作業終了日時:
            = i.datetime_select :finish, {}, class: 'Form__Admission__Child__Datetime-Finish__Pulldown'
          = i.text_field :prace, placeholder: "場所", class: "Form__Admission__Child__Text-field"
          .Form__Admission__Child__Check-box
            高所作業：
            = i.check_box :aerial, class: "Form__Admission__Child__Check-box__Aerial"
          .Form__Admission__Child__Check-box
            火器使用：
            = i.check_box :firearm, class: "Form__Admission__Child__Check-box__Firearm"
          .Form__Admission__Child__Check-box
            = i.text_area :notice, placeholder: "特記事項", class: "Form__Admission__Child__Text-area"
        .Form__Admission__Child
          .Form__Admission__Child__Subtitle
            作業者情報
          = i.text_field :campany, placeholder: "会社名", class: "Form__Admission__Child__Text-field"
          = i.text_field :representative, placeholder: "代表者名", class: "Form__Admission__Child__Text-field"
          = i.text_field :tell, placeholder: "000-0000-0000", class: "Form__Admission__Child__Text-field"
          = i.text_field :worker1, placeholder: "作業者1", class: "Form__Admission__Child__Text-field"
          = i.text_field :worker2, placeholder: "作業者2", class: "Form__Admission__Child__Text-field"
          = i.text_field :worker3, placeholder: "作業者3", class: "Form__Admission__Child__Text-field"
          = i.text_field :worker4, placeholder: "作業者4", class: "Form__Admission__Child__Text-field"
    .Form__Document
      = form.file_field :pdf
  = form.submit value: "SEND", class: "Form__Send"

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button'
    = link_to "トップページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'